# Generated by Django 2.0.4 on 2018-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
